### ISSUE TITLE
Problem with MAC M1

### ISSUE THREAD

**Issue by FelipeRodriguezFonte** [nathan-fiscaletti/advanced-screen-streamer#1]
Hello 

I have a mac M1 and I always get the same error that the file is corrupted and I have to move it to the trash. Does it work with these devices?

**Comment by nathan-fiscaletti** [comment]
It should be working. Can you try downloading the source code and re-building the DMG? You can do so by running the following command.
```sh
$ yarn electron:package:mac
```

**Comment by nathan-fiscaletti** [comment]
See the newly created [FAQ](https://github.com/nathan-fiscaletti/framecast?tab=readme-ov-file#faq) for more information on resolving this issue.
